# Generated by Django 4.1 on 2022-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bidder',
            field=models.BooleanField(default=False),
        ),
    ]
