# Generated by Django 4.1 on 2022-08-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bio',
        ),
    ]
