# Generated by Django 4.1 on 2022-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
