# Generated by Django 4.1 on 2022-09-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_user_is_accepted_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
    ]
