# Generated by Django 4.1 on 2022-09-09 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_category_remove_auction_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL),
        ),
    ]
