# Generated by Django 4.1 on 2022-09-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
