# Generated by Django 4.1 on 2022-09-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='userId',
            new_name='userid',
        ),
    ]
