# Generated by Django 4.1 on 2022-09-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='itemId',
        ),
    ]
