# Generated by Django 4.1 on 2022-09-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_remove_auction_seller_auction_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='categories',
        ),
        migrations.AddField(
            model_name='auction',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
