# Generated by Django 4.1 on 2022-09-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_remove_auction_categories_auction_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='categories',
        ),
        migrations.AddField(
            model_name='auction',
            name='categories',
            field=models.ManyToManyField(to='auctions.category'),
        ),
    ]
