# Generated by Django 4.1 on 2022-09-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_bid_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='time',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='userid',
        ),
    ]
