# Generated by Django 4.1 on 2022-09-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_remove_auction_bids_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
    ]
