# Generated by Django 4.1 on 2022-09-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bidders',
        ),
    ]
