# Generated by Django 4.1 on 2022-09-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_bid_amount_bid_time_bid_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='auctionid',
            field=models.ManyToManyField(to='auctions.auction'),
        ),
    ]
