# Generated by Django 4.1 on 2022-09-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_remove_auction_bids_bid_auctionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auctionid',
        ),
        migrations.AddField(
            model_name='bid',
            name='auctionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionid', to='auctions.auction'),
        ),
    ]
