# Generated by Django 4.1 on 2022-10-08 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auction_latitude_auction_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recAuctions', models.ManyToManyField(to='auctions.auction')),
                ('recUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
