# Generated by Django 4.1 on 2022-10-08 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_recommendeditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='visitors',
            field=models.ManyToManyField(related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
