# Generated by Django 4.1 on 2022-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='visitors',
        ),
        migrations.AddField(
            model_name='bid',
            name='ds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
