# Generated by Django 4.1 on 2022-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_remove_auction_visitors_bid_ds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='ds',
        ),
        migrations.AddField(
            model_name='bid',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
