# Generated by Django 4.1 on 2022-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_remove_bid_ds_bid_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='isOpen',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
