# Generated by Django 4.1 on 2022-10-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_alter_auction_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='RecommendedItems',
        ),
    ]
